services:
  db: 
    image: postgres
    container_name: job-tracker-db
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=job_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    # restart: always
    ports:
      - "8080:8080"

  backend:
    container_name: job-tracker-backend
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=job_tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PORT=8000
      - JWT_ACCESS_SECRET=super-access-secret-change-me
      - JWT_REFRESH_SECRET=super-refresh-secret-change-me
      - ACCESS_TOKEN_EXPIRES=15m
      - REFRESH_TOKEN_EXPIRES=7d

volumes:
  postgres_data: